-- FindBack — initial PostgreSQL schema (Supabase).
-- Mirrors services/api/src/db/sqliteAdapter.ts (SQLITE_SCHEMA).
-- Apply with `npm run db:migrate` once DATABASE_URL points at the project.
--
-- Conventions kept from the SQLite build so the API layer is unchanged:
--   * TEXT primary keys (UUIDs generated by the app) and TEXT ISO-8601 timestamps
--   * integer 0/1 booleans (email_verified / phone_verified)
--   * case-insensitive uniqueness via UNIQUE INDEX on lower(...)

create table if not exists users (
  id text primary key,
  username text not null,
  email text not null,
  phone text not null,
  password_hash text not null,
  email_verified integer not null default 0,
  phone_verified integer not null default 0,
  avatar_url text,
  created_at text not null,
  updated_at text not null
);

create unique index if not exists ux_users_username_lower on users (lower(username));
create unique index if not exists ux_users_email_lower on users (lower(email));
create unique index if not exists ux_users_phone_lower on users (lower(phone));

create table if not exists item_posts (
  id text primary key,
  user_id text not null references users(id) on delete cascade,
  type text not null check (type in ('LOST', 'FOUND')),
  title text not null,
  description text not null,
  category text not null,
  status text not null default 'OPEN'
    check (status in ('OPEN', 'MATCHED', 'RECOVERED', 'CLOSED')),
  event_date text not null,
  latitude double precision,
  longitude double precision,
  location_label text,
  youtube_url text,
  created_at text not null,
  updated_at text not null
);

create table if not exists attachments (
  id text primary key,
  post_id text not null references item_posts(id) on delete cascade,
  file_url text not null,
  mime_type text not null,
  file_name text not null,
  file_size integer not null,
  created_at text not null
);

create table if not exists comments (
  id text primary key,
  post_id text not null references item_posts(id) on delete cascade,
  user_id text not null references users(id) on delete cascade,
  body text not null,
  created_at text not null,
  updated_at text not null
);

create table if not exists reactions (
  id text primary key,
  post_id text not null references item_posts(id) on delete cascade,
  user_id text not null references users(id) on delete cascade,
  type text not null check (type in ('LIKE', 'DISLIKE')),
  created_at text not null,
  unique (post_id, user_id)
);

create table if not exists ratings (
  id text primary key,
  post_id text not null references item_posts(id) on delete cascade,
  user_id text not null references users(id) on delete cascade,
  score integer not null check (score between 1 and 5),
  created_at text not null,
  updated_at text not null,
  unique (post_id, user_id)
);

create table if not exists verification_challenges (
  id text primary key,
  user_id text not null references users(id) on delete cascade,
  channel text not null check (channel in ('EMAIL', 'PHONE')),
  code_hash text not null,
  expires_at text not null,
  verified_at text,
  created_at text not null
);

create table if not exists uploads (
  id text primary key,
  user_id text not null references users(id) on delete cascade,
  file_name text not null,
  mime_type text not null,
  file_size integer not null,
  file_url text not null,
  created_at text not null
);

create index if not exists idx_posts_type_created on item_posts (type, created_at desc);
create index if not exists idx_posts_category on item_posts (category);
create index if not exists idx_posts_user on item_posts (user_id);
create index if not exists idx_comments_post on comments (post_id, created_at);
create index if not exists idx_challenges_user_channel on verification_challenges (user_id, channel);
